### PR TITLE
Bugfixing/sparta 666 userpluginsjar not running

### PR DESCRIPTION
**Pull request by danielcsant**
- JDBC output documented:
https://stratio.atlassian.net/wiki/display/SPARKTA/Outputs#Outputs-JDBC

- User jar plugins bugfixed

- User plugin example
https://stratio.atlassian.net/wiki/display/SPARKTA/SDK

- Added logging traces

### CODE REVIEW

**Comment by compae** [comment]
:shipit:

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/Sparta/job/CD/3483/)

**Comment by compae** [comment]
Nice!! very Nice!!

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Pull request merged**
