### PR TITLE
Sparkta 431 fix demo policy

### PR DESCRIPTION
**Pull request by dvallejo**
- Fixed demo with orders
- Added new Geo Parser

[Ticket in JIRA](https://stratio.atlassian.net/browse/SPARKTA-431)

### CODE REVIEW

**Comment by compae** [comment]
LGTM

**Comment by danielcsant** [comment]
+1

**Comment by acemilio** [comment]
+1

**Comment by antonioalf** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Pull request merged**
