### PR TITLE
Change in dockerentrypoint the Stratio tools URL

### PR DESCRIPTION
**Pull request by gbecares**

### CODE REVIEW

**Comment by gbecares** [comment]
:shipit:

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/Sparta/job/CD/3184/)

**Comment by gbecares** [comment]
:shipit:

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/Sparta/job/CD/3192/)

**Comment by pbedia-stratio** [comment]
:shipit:

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/Sparta/job/CD/3196/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Pull request merged**
