### PR TITLE
[SPARKTA-449] Improve performance in cube and cubemaker

### PR DESCRIPTION
**Pull request by compae**
###### Description

Avoid Spark shuffle with mapPartitions and removing filter with map.

### CODE REVIEW

**Comment by anistal** [comment]
+1

**Comment by acemilio** [comment]
+1, but it would be a good idea to split Cube.scala class into some traits (e.g. AssociativeOperatorUtils, NonAssociativeOperatorUtils, ...), in order to lighten up this class.

**Comment by antonioalf** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Comment by antonioalf** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Pull request merged**
