### PR TITLE
SPARKTA-393 fix CustomExceptionHandler behaviour

### PR DESCRIPTION
**Pull request by acemilio**
Removed implicit handler from some classes in order to use expected CustomExceptionHandler.

### CODE REVIEW

**Comment by compae** [comment]
The exception handler is removed, we don't need this?

**Comment by acemilio** [comment]
We don't need implicit handler within controllers.  We've already got a
CustomExceptionHandler class that we were not using.

On Tue, Feb 16, 2016, 12:25 AM Jose Carlos Garcia Serrano <
notifications@github.com> wrote:

> The exception handler is removed, we don't need this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stratio/Sparta/pull/1399#issuecomment-184439320>.
>
-- 


Emilio Ambrosio Cordero | Big Data Developer
@_eambrosioc

Vía de las Dos Castillas, 33, Ática 4, 3ª Planta.
28224 Pozuelo de Alarcón. Madrid.
+34 918286473 // *@stratiobd <https://twitter.com/StratioBD>*

**Comment by compae** [comment]
LGTM

**Comment by anistal** [comment]
All ok

**Pull request merged**
