### PR TITLE
[SPARKTA-219] [SDK,AGGREGATOR] Cube functions for updates only the dimensions changed

### PR DESCRIPTION
**Pull request by compae**
#### Description

New functions in Cube in order to mark the dimensionsValues that are changed on the actual streaming window, if are been changed this values must be upserted in the Output. 
Refactor names.

SPARKTA-219
#### Reviewer

@danielcsant 
#### Test

All passed.

### CODE REVIEW

**Comment by danielcsant** [comment]
Same error in test-at

**Comment by sgomezg** [comment]
Same result over here :(

**Comment by gserranojc** [comment]
Removing the .m2 pass all tests.

**Comment by Gschiavon** [comment]
Ok if test-at don't change. I think they should be exactly the same.

**Comment by danielcsant** [comment]
+1 test-at success

**Comment by sgomezg** [comment]
+1

**Pull request merged**
