### PR TITLE
[SPARKTA-420][WEB]: Fix policy outputs when user is creating or editing a policy

### PR DESCRIPTION
**Pull request by EvaMGC**

### CODE REVIEW

**Comment by MarioStratio** [comment]
LGTM

**Comment by compae** [comment]
Only one commit. Please squash them.

**Comment by antonioalf** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Pull request merged**
