### PR TITLE
[SPARTA-608] Remove AssertAspect from aop.xml file

### PR DESCRIPTION
**Pull request by gbecares**

### CODE REVIEW

**Comment by antonioalf** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by antonioalf** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Pull request merged**
