### PR TITLE
Sparta-644 Fragments filled

### PR DESCRIPTION
**Pull request by danielcsant**

### CODE REVIEW

**Comment by compae** [comment]
Update banch and then we can merge this PR.

**Comment by compae** [comment]
:shipit:

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/Sparta/job/CD/3462/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Comment by witokondoria** [comment]
:shipit:

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/Sparta/job/CD/3470/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Pull request merged**
