### PR TITLE
[SPARKTA-462] Updated Cassandra connector

### PR DESCRIPTION
**Pull request by danielcsant**
Platform epic: https://stratio.atlassian.net/browse/PLATFORM-88

### CODE REVIEW

**Comment by acemilio** [comment]
+1

**Comment by anistal** [comment]
+1

**Comment by antonioalf** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Pull request merged**
