### PR TITLE
[SPARTA-600] [DRIVER] [SERVING-API] [WEB] Slide window added to stream triggers

### PR DESCRIPTION
**Pull request by compae**
**Given** a policy with one stream trigger
**When** I add the slidding window
**Then** the policy should run and check the correct value of the spark streaming window property

### CODE REVIEW

**Comment by EvaMGC** [comment]
Add "--no color" argument to build task in pom file

**Comment by compae** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP on [Jenkins](http://jenkins.stratio.com/job/Sparta/job/CD/3013/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Pull request merged**
