### PR TITLE
[SPARKTA-352] Refactor rpm/deb generation

### PR DESCRIPTION
**Pull request by danielcsant**
- Made changes according https://stratio.atlassian.net/wiki/display/PRODUCT/Linux+packaging
- Fixed log bug. It seems we exclude log4j library and Sparkta was looking for logback.xml

### CODE REVIEW

**Comment by anistal** [comment]
+1

**Comment by antonioalf** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Pull request merged**
