### PR TITLE
[SPARKTA-420][WEB]: Fix bugs to json generated by policy wizard

### PR DESCRIPTION
**Pull request by EvaMGC**
* Remove unused attributes from final json generated by wizard
* Formatted sparkStreamingWindow attribute to the agreed format

### CODE REVIEW

**Comment by MarioStratio** [comment]
LGTM

**Comment by antonioalf** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Pull request merged**
