### PR TITLE
[SPARTA-360] [SPARTA-510] Integration with GoSec

### PR DESCRIPTION
**Pull request by anistal**
#### Description
With this feature you can configure a SSO server. For this purpose you need to follow these steps:

- Add in your /etc/hosts: 
```
10.200.0.56 gosec01.dev.stratio.com
127.0.0.1 anistal
```
- Download the certification from: https://gosec01.dev.stratio.com:9005/cas/login (export Gosec's SSL certification with chrome/firefox/etc.)
- Create cacerts file: 
```
keytool -import -alias ca -file Stratio\ Inc\ CA -keystore cacerts -storepass stratio
```
- Run sparta with this option -Djavax.net.ssl.trustStore=/path/to/cacerts
- Configure your application.conf with oauth configuration:
```
oauth2 {
  enable = "true"
  
  url {
    authorize = "https://gosec01.dev.stratio.com:9005/cas/oauth2.0/authorize"
    accessToken = "https://gosec01.dev.stratio.com:9005/cas/oauth2.0/accessToken"
    profile = "https://gosec01.dev.stratio.com:9005/cas/oauth2.0/profile"
    logout = "https://gosec01.dev.stratio.com:9005/cas/logout"
    callBack = "http://anistal:9090/login"
    onLoginGoTo = "/"
  }
  client{
    id = "anistal-client"
    secret = "fg345vfdefgh4gweb424rtvwg24"
  }
  cookieName="user"
}
```
- Starts sparta and go to the main page. When it appears you should be redirected to the login page
- Enter username and password: jmgomez/1234 (test user to check).
- The user is logged. If you need to do a logout: http://localhost:9090/logout. The cookie will be removed.

#### Definition of Done
**GIVEN** a running Sparta instance
**WHEN** you try to access to the main page
**THEN** you should be redirected to the SSO page

#### Documentation
https://stratio.atlassian.net/wiki/display/SPARKTA/6.+Configuration#id-6.Configuration-5.8.Oauth

### CODE REVIEW

**Comment by acemilio** [comment]
trying to test but redirect bug has been detected again. Pending @anistal and @EvaMGC review

**Comment by acemilio** [comment]
+1

**Comment by antonioalf** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Pull request merged**
