### PR TITLE
[SPARKTA-486] [EXAMPLES] Advanced Twitter policies with triggers and multiple outputs

### PR DESCRIPTION
**Pull request by compae**
***given*** an instance of Sparta
***when*** you want to make one policy with triggers and outputs from Twitter
***then*** you have examples for this use case

### CODE REVIEW

**Comment by acemilio** [comment]
+1 but I miss some **DOD's** within above description box

**Comment by danielcsant** [comment]
+1 The same with the DOD

**Comment by antonioalf** [comment]
:shipit:

**Comment by antonioalf** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Pull request merged**
