### PR TITLE
[SPARTA-622][WEB]: Geo parser cannot be configured from UI

### PR DESCRIPTION
**Pull request by EvaMGC**
**Given** a policy wizard
**When** I am creating a transformation
**And** I select 'geo parser' type
**Then** input field is not shown.

**Given** a policy wizard
**When** I am creating a transformation
**And** I select 'geo parser' type
**And** I add a new output field
**Then** I can only select 'String' as type.

### CODE REVIEW

**Comment by danielcsant** [comment]
default configuration appears:

```
{
  "latitude": "lat",
  "longitude": "long",
  "inputFormat": "unixMillis"
}
```

should be:

```
{
  "latitude": "lat",
  "longitude": "long"
}
```

**Comment by danielcsant** [comment]
Still happening. 
First time appears properly but going to another type and going back to the GeoParser it is wrong

**Comment by danielcsant** [comment]
+1

**Comment by gbecares** [comment]
Output Fields box is not disabled when the user tries to edit it.

**Comment by gbecares** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Pull request merged**
