### PR TITLE
Akka dependency unified

### PR DESCRIPTION
**Pull request by compae**

### CODE REVIEW

**Comment by danielcsant** [comment]
LGTM. It is important to test this change against YARN and Mesos since they provided an Akka dependency

**Comment by gbecares** [comment]
:shipit:

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/Sparta/job/CD/3101/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/Sparta/job/CD/3106/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Pull request merged**
