### PR TITLE
[SPARKTA-522] Exclude /var in pom.xml

### PR DESCRIPTION
**Pull request by anistal**
#### Description
Minor change to add /var as a path to exclude in dist pom.xml

### CODE REVIEW

**Comment by acemilio** [comment]
+1

**Comment by danielcsant** [comment]
+1

**Comment by antonioalf** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Pull request merged**
