### PR TITLE
SPARKTA-415 Fixed bug with Java 7 in waitFor method

### PR DESCRIPTION
**Pull request by dvallejo**
Fixed bug with Java 7.

Method waitFor(timeout, timeformat) is not available in Java 7 (only for Java 8).
I've used the method waitFor() without timeout ([Documentation here](https://docs.oracle.com/javase/8/docs/api/java/lang/Process.html#waitFor--))

[Ticket in Jira](https://stratio.atlassian.net/browse/SPARKTA-415)

### Definition of Done

- Using Java 7 Spark should be launched properly in cluster mode
- Using Java 8 Spark should be launched properly in cluster mode

### CODE REVIEW

**Comment by danielcsant** [comment]
+1

**Comment by anistal** [comment]
+1

**Comment by antonioalf** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Pull request merged**
