### PR TITLE
[SPARTA-551]: As a user I want to create a policy without any cube

### PR DESCRIPTION
**Pull request by EvaMGC**
**Given** an sparkta instance
**When** I want to create a policy without any cube
**Then** two errors are shown saying that:
 - an output at least is required
 - policy needs a cube or trigger at least

**Given** an sparkta instance
**When** I want to create a policy without any cube but with a stream trigger (without outputs)
**Then** an error is shown saying that at least an output is required

**Given** an sparkta instance
**When** I want to create a policy with an output
**Then** policy is successfully created

**NOTE:**  It was neccessary to refactor the error policy management in order to support associated errors.

### CODE REVIEW

**Comment by antonioalf** [comment]
- Certain messages are not translated:
_ERROR_100_ in inputs and outputs
_RUN_POLICY_KO when trying to run policy that is already running

- In Flume input, in push type, Decompression is not really optional, it has to be checked to be able to create input

**Comment by antonioalf** [comment]
Typo: "_ERROR_ALL_FIELDS_REQUIRED_": "All fields are required! Please check them and try to sumbit the form."

**Comment by antonioalf** [comment]
Typo: "_300_": "There was an error. There is not a template whit this name!",

**Comment by antonioalf** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Pull request merged**
